### ISSUE TITLE
OidcApiAuthorizationService returns successful authentication when token validation retry throws SecurityTokenSignatureKeyNotFoundException

### ISSUE THREAD

**Issue by k1v** [bryanknox/AzureFunctionsOpenIDConnectAuthSample#28]
Hi. Thank you for your work and this repo. I think I may have found an issue with OidcApiAuthorizationService. If token validation throws a SecurityTokenSignatureKeyNotFoundException and the same exception is thrown again during the retry then OidcApiAuthorizationService will return a successful authentication result.

**Comment by k1v** [comment]
I have created a pull request #29

**Comment by bryanknox** [comment]
Great catch @k1v!
