### ISSUE TITLE
Publish OidcApiAuthorization as NuGet package

### ISSUE THREAD

**Issue by bryanknox** [bryanknox/AzureFunctionsOpenIDConnectAuthSample#39]
Create and publish the OidcApiAuthorization class library as a NuGet package.

**Comment by bryanknox** [comment]
I have no idea right now when I might be able to create a NuGet package for the OidcApiAuthorization library.  Seems like it would be helpful to people.

@Invvard asked about that back in September 2020. And @sizzle168 asked a few days ago.

**Comment by SeanFeldman** [comment]
I can give a hand.

**Comment by bryanknox** [comment]
Hi @SeanFeldman, help would be awesome. Direct message me on Twitter at [bryanknoxbits](https://twitter.com/bryanknoxbits), and we can discuss.

**Comment by bryanknox** [comment]
Here are some of my thoughts on names for the NuGet package. I'd like to hear other ideas too.

- The library is named `OidcApiAuthorization`, but I don't like that as the package name.

- The library name and namespace should be changed to match the package name. It will help reduce friction for devs using the package if the library and namespace all match the package name.

- I think it should be clear that the package is for use in Azure Functions. Technically there might be other places that the package could be used but I think its important that the package be focused on use in Azure Functions. So I'm strongly leaning toward `AzureFunctions.` as the package name prefix.

- The package is also focused on use in HTTP triggered Azure Functions. So I'd like to extend the prefix to be something like `AzureFunctions.HTTP.`.

- Authorization is also a key intent of the package. So I'd like to extend the prefix to be something like `AzureFunctions.HTTP.Auth`.

- The package is very specific to OpenID Connect (OIDC). So that should be indicated in the package name as well.

Here are my proposals for the package name: 
- `AzureFunctions.HTTP.Auth.Oidc`
- `AzureFunctions.HTTP.Auth.OpenIdConnect`

I tend toward verbose names and like the second one best.

I think either of these names would be good and help devs understand the intent of the package.

I'd really like to get feedback on these. Names are hard and I'd like to hear other ideas.

**Comment by SeanFeldman** [comment]
> OpenID Connect (OIDC) is an open authentication protocol that profiles and extends OAuth 2.0 to add an identity layer. OIDC allows clients to confirm an end user’s identity using authentication by an authorization server. Implementing OIDC on top of OAuth 2.0 creates a single framework that promises to secure APIs, mobile native applications and browser applications in a single, cohesive architecture.

Based on the [definition](https://www.pingidentity.com/en/resources/content-library/articles/openid-connect.html) of OIDC, having ‘HTTP’ or ‘Auth’ is redundant. Choosing between ’OIDC’ and ‘OpenIdConnect’, the latter is less obfuscated than its abbreviation. My vote would be to use `AzureFunctions.OpenIdConnect`.

**Comment by SeanFeldman** [comment]
BTW there’s a [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) project that also supports [Authorize](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect/blob/main/src/AzureFunctions.Extensions.OpenIDConnect.Tests/RouteGuardianShould.cs) attribute with [policies](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect/blob/main/src/AzureFunctions.Extensions.OpenIDConnect.Tests/AuthorizationServiceShould.cs). NuGet [package](https://www.nuget.org/packages/AzureFunctions.Extensions.OpenIDConnect/) is available.

@bryanknox perhaps worth reviewing that first prior to any further effort investment?

**Comment by bryanknox** [comment]
> BTW there’s a [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) project that also supports [Authorize](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect/blob/main/src/AzureFunctions.Extensions.OpenIDConnect.Tests/RouteGuardianShould.cs) attribute with [policies](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect/blob/main/src/AzureFunctions.Extensions.OpenIDConnect.Tests/AuthorizationServiceShould.cs). NuGet [package](https://www.nuget.org/packages/AzureFunctions.Extensions.OpenIDConnect/) is available.

I took a quick look and it's based on code from this repo! The authorization stuff looks interesting. I'll look deeper into it. I'm curious if it can be used in middleware.
What are your thoughts on it @SeanFeldman?

**Comment by SeanFeldman** [comment]
I think technically it could. The nice part about `Authorize` attribute support that it could be based on policies and that would not go into middleware but rather specific functions. Which makes sense.

> I took a quick look and it's based on code from this repo! 

Does that mean that [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) supersedes this repo? And if so, is there a point of having the two?

**Comment by bryanknox** [comment]
> Does that mean that [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) supersedes this repo? And if so, is there a point of having the two?

This repo's original purpose was to show a way that OIDC could be implemented for Azure Functions, while the [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) repo   is focused on providing reuse via the associated NuGet package.  If that NuGet package solves the problem we were trying to address by publishing a NuGet package from this repo, then it might be better to use that NuGet and consider contributing to that repo.

Right now, I'm thinking that we should not add a NuGet package to this repo.

**Comment by SeanFeldman** [comment]
@bryanknox agreed.

Well, this was the quickest help I've ever provided 😂

**Comment by bryanknox** [comment]
Well, if nothing else @SeanFeldman you helped bring some awareness of the [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) repo and [NuGet](https://www.nuget.org/packages/AzureFunctions.Extensions.OpenIDConnect/).

**Comment by bryanknox** [comment]
Closing this issue. There won't be a NuGet out of this repo. 

See the [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) repo and [NuGet](https://www.nuget.org/packages/AzureFunctions.Extensions.OpenIDConnect/). That repo was forked from https://github.com/AspNetMonsters/AzureFunctions.OidcAuthentication which was originally forked from this repo. So there you go.

**Comment by bryanknox** [comment]
Closing this issue. There won't be a NuGet out of this repo. 

See the [AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) repo and [NuGet](https://www.nuget.org/packages/AzureFunctions.Extensions.OpenIDConnect/). 

That repo was forked from https://github.com/AspNetMonsters/AzureFunctions.OidcAuthentication which was originally forked from this repo. So there you go.

**Comment by bryanknox** [comment]
Also see the [AspNetMonsters/AzureFunctions.OidcAuthentication](https://github.com/AspNetMonsters/AzureFunctions.OidcAuthentication) repo and [NuGet](https://www.nuget.org/packages/AzureFunctions.OidcAuthentication/) that was originally forked from this repo.
