### ISSUE TITLE
Does not work with isolated function 

### ISSUE THREAD

**Issue by Gautam2010** [bryanknox/AzureFunctionsOpenIDConnectAuthSample#42]
Does not support authentication with isolated function 
https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

**Comment by SeanFeldman** [comment]
See https://github.com/bryanknox/AzureFunctionsOpenIDConnectAuthSample/issues/39#issuecomment-1140626186

**Comment by bryanknox** [comment]
Closing this issue with no changes. For support in isolated-process functions see  [fmichellonet/AzureFunctions.Extensions.OpenIDConnect](https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect) repo and [NuGet](https://www.nuget.org/packages/AzureFunctions.Extensions.OpenIDConnect/)
